package io.github.premwadhwani24.resumeanalyzer.resumeanalyzer.User;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

// Represents a user entity in the application
@Entity
@Table(name = "users")
@Getter // Generates getter methods
@Setter // Generates setter methods
@NoArgsConstructor // Default constructor for JPA
@AllArgsConstructor // Constructor with all fields
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Based only on explicitly included fields
@ToString(exclude = "password") // Exclude password from toString method for security
public class User {

    // Unique identifier, autogenerated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    // Name of the user, must not be blank
    @NotBlank(message = "Name cannot be empty.")
    private String name;

    // User's email, unique and must be a valid email format
    @Email(message = "Invalid email format.")
    @NotBlank(message = "Email is required.")
    @Column(unique = true)
    private String email;

    // User's password with minimum length requirement
    @Size(min = 6, message = "Password must be at least 6 characters.")
    @NotBlank(message = "Password cannot be blank.")
    private String password;
}