package io.github.premwadhwani24.resumeanalyzer.resumeanalyzer.Resume;

import io.github.premwadhwani24.resumeanalyzer.resumeanalyzer.User.User;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.PastOrPresent;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Represents a Resume entity that stores uploaded resume details,
 * including the file name, parsed skills, upload date, and the user who uploaded it.
 * This entity is mapped to the "resumes" table in the database.
 */
@Entity
@Table(name = "resumes")
public class Resume {

    /** Unique identifier for each resume. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the uploaded resume file. Cannot be blank. */
    @NotBlank(message = "File name is required.")
    private String fileName;

    /** Skills parsed from the resume, stored as a string. */
    @Column(length = 1000)
    private String parsedSkills;

    /** Date the resume was uploaded. Must be today or a past date. */
    @PastOrPresent(message = "Upload date must be today or in the past.")
    private LocalDate uploadedAt;

    /** The user who uploaded the resume. Linked through foreign key user_id. */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Default constructor. Required by JPA. */
    public Resume() {}

    /** Parameterized constructor for convenience. */
    public Resume(Long id, String fileName, String parsedSkills, LocalDate uploadedAt, User user) {
        this.id = id;
        this.fileName = fileName;
        this.parsedSkills = parsedSkills;
        this.uploadedAt = uploadedAt;
        this.user = user;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getParsedSkills() {
        return parsedSkills;
    }

    public void setParsedSkills(String parsedSkills) {
        this.parsedSkills = parsedSkills;
    }

    public LocalDate getUploadedAt() {
        return uploadedAt;
    }

    public void setUploadedAt(LocalDate uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Checks if two Resume objects are equal based on their fields.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Resume resume = (Resume) o;
        return Objects.equals(id, resume.id) &&
                Objects.equals(fileName, resume.fileName) &&
                Objects.equals(parsedSkills, resume.parsedSkills) &&
                Objects.equals(uploadedAt, resume.uploadedAt) &&
                Objects.equals(user, resume.user);
    }

    /**
     * Generates a hash code based on the resume's fields.
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, fileName, parsedSkills, uploadedAt, user);
    }

    /**
     * Returns a string representation of the Resume object.
     */
    @Override
    public String toString() {
        return "Resume{" +
                "id=" + id +
                ", fileName='" + fileName + '\'' +
                ", parsedSkills='" + parsedSkills + '\'' +
                ", uploadedAt=" + uploadedAt +
                ", user=" + user +
                '}';
    }
}
